name: attendance_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http:
  image_picker: ^1.0.7
  animated_bottom_navigation_bar: ^1.3.3
  circular_reveal_animation: ^2.0.1
  auto_size_text: ^3.0.0
  dio: ^5.5.0+1
  connectivity_plus: ^5.0.2
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  camera: ^0.10.5+9
  permission_handler: ^11.0.1
  percent_indicator: ^4.2.3
  pdf: ^3.11.0
  path_provider: ^2.1.2
  email_validator: ^3.0.0
  shared_preferences: ^2.2.2
  bottom_navy_bar: ^6.1.0
  convex_bottom_bar: ^3.2.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  web:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
